"""In-app notifications — what the bell in the header shows.

WHO A NOTIFICATION IS FOR. `user_id` NULL means everyone in the workspace. That is the
normal case for a contract reminder: series contracts are scoped to the tenant, not to the
person who keyed them in (see models/series.py), and a deposit due tomorrow must reach
whoever is at a desk, not only a colleague who is on leave. `user_id` set means one
person — "the contract you uploaded has been read, review it" is nobody else's business.

WHY READ STATE IS A SEPARATE TABLE. A broadcast row is shared, so "read" cannot be a
column on it: one person opening it must not clear it for the other nine.

WHY `dedupe_key`. Reminders are generated by re-scanning live deadlines rather than by a
scheduler (there is none in this stack), so the same scan runs many times a day. The
unique (tenant_id, dedupe_key) makes that idempotent — a reminder is written the first
time its stage is reached and never again. The key carries the date the reminder is about,
so a deadline that moves raises a fresh reminder instead of hiding behind the old one.
"""
from datetime import date, datetime

from sqlalchemy import (
    CheckConstraint, Date, DateTime, ForeignKey, Index, Integer, String, UniqueConstraint,
)
from sqlalchemy.orm import Mapped, mapped_column

from app.database import Base

SEVERITIES: tuple[str, ...] = ("info", "success", "warning", "critical")


class Notification(Base):
    __tablename__ = "notifications"
    __table_args__ = (
        CheckConstraint(
            "severity IN (" + ", ".join(f"'{s}'" for s in SEVERITIES) + ")",
            name="ck_notifications_severity",
        ),
        UniqueConstraint("tenant_id", "dedupe_key", name="uq_notifications_tenant_dedupe"),
        # The bell: newest first for one workspace.
        Index("ix_notifications_tenant_created", "tenant_id", "created_at"),
    )

    id:        Mapped[int]        = mapped_column(primary_key=True)
    tenant_id: Mapped[int | None] = mapped_column(Integer, ForeignKey("tenants.id", ondelete="CASCADE"), nullable=True, index=True)
    # NULL = the whole workspace.
    user_id:   Mapped[int | None] = mapped_column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=True, index=True)

    # Which screen raised it — "series" for contracts. The Series page filters on this to
    # show its own reminders above the list.
    category: Mapped[str]        = mapped_column(String(30), nullable=False)
    kind:     Mapped[str]        = mapped_column(String(40), nullable=False)
    severity: Mapped[str]        = mapped_column(String(10), nullable=False, server_default="info", default="info")
    title:    Mapped[str]        = mapped_column(String(200), nullable=False)
    body:     Mapped[str | None] = mapped_column(String(500), nullable=True)
    # A frontend route, e.g. /vendors/series-sit-mice/12.
    link:     Mapped[str | None] = mapped_column(String(300), nullable=True)
    # The date the notification is about (a due date), for sorting and for "in 3 days".
    due_date: Mapped[date | None] = mapped_column(Date, nullable=True)

    source_type: Mapped[str | None] = mapped_column(String(40), nullable=True)
    source_id:   Mapped[int | None] = mapped_column(Integer, nullable=True)
    dedupe_key:  Mapped[str]        = mapped_column(String(200), nullable=False)

    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)


class NotificationRead(Base):
    """One person has read (or dismissed) one notification."""
    __tablename__ = "notification_reads"
    __table_args__ = (
        UniqueConstraint("notification_id", "user_id", name="uq_notification_reads_user"),
        Index("ix_notification_reads_user", "user_id"),
    )

    id:              Mapped[int]        = mapped_column(primary_key=True)
    tenant_id:       Mapped[int | None] = mapped_column(Integer, ForeignKey("tenants.id", ondelete="CASCADE"), nullable=True, index=True)
    notification_id: Mapped[int]        = mapped_column(Integer, ForeignKey("notifications.id", ondelete="CASCADE"), nullable=False)
    user_id:         Mapped[int]        = mapped_column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    read_at:         Mapped[datetime]   = mapped_column(DateTime, default=datetime.utcnow)
