from fastapi import APIRouter

from app.api.v1 import auth, users, airlines, suppliers, airports, routes, deals, tickets, income, documents, reports, classes, approval_workflows, dashboard, customers, corporates, entities, login_ids, iata_commissions, user_entities, user_login_ids, agencies, agency_entities, agency_login_ids, agency_billing, adjustments, airline_adjustments, statements, bsp, bsp_summary, bsp_reconciliation, bsp_commission, customer_statements, lcc_detailed, ticket_details, series_contracts

router = APIRouter()

router.include_router(auth.router, prefix="/auth", tags=["Auth"])
router.include_router(users.router, prefix="/users", tags=["Users"])
router.include_router(airlines.router, prefix="/airlines", tags=["Airlines"])
router.include_router(suppliers.router, prefix="/suppliers", tags=["Suppliers"])
router.include_router(airports.router, prefix="/airports", tags=["Airports"])
router.include_router(routes.router, prefix="/routes", tags=["Routes"])
router.include_router(deals.router, prefix="/deals", tags=["Deals"])
router.include_router(tickets.router, prefix="/tickets", tags=["Tickets"])
router.include_router(income.router, prefix="/income", tags=["Income"])
router.include_router(documents.router, prefix="/documents", tags=["Documents"])
router.include_router(reports.router, prefix="/reports", tags=["Reports"])
router.include_router(classes.router, prefix="/classes", tags=["Classes"])
router.include_router(approval_workflows.router, prefix="/approval-workflows", tags=["Approval Workflows"])
router.include_router(dashboard.router, prefix="/dashboard", tags=["Dashboard"])
router.include_router(customers.router, prefix="/customers", tags=["Customers"])
router.include_router(corporates.router, prefix="/corporates", tags=["Corporate Billing"])
router.include_router(entities.router, prefix="/entities", tags=["User Master - Entities"])
router.include_router(login_ids.router, prefix="/login-ids", tags=["User Master - Login IDs"])
router.include_router(iata_commissions.router, prefix="/iata-commissions", tags=["User Master - IATA Commission"])
router.include_router(user_entities.router, prefix="/user-entities", tags=["My Profile - Entities"])
router.include_router(user_login_ids.router, prefix="/user-login-ids", tags=["My Profile - Login IDs"])
router.include_router(agencies.router, prefix="/agencies", tags=["Agency Profile - Agencies"])
router.include_router(agency_entities.router, prefix="/agency-entities", tags=["Agency Profile - Entities"])
router.include_router(agency_login_ids.router, prefix="/agency-login-ids", tags=["Agency Profile - Login IDs"])
router.include_router(agency_billing.router, prefix="/agency-billings", tags=["Agency Billing"])
router.include_router(adjustments.router, prefix="/adjustments", tags=["Tickets - Airline Adjustments"])
router.include_router(airline_adjustments.router, prefix="/airline-adjustments", tags=["Tickets - Airline Adjustments (ADM/ACM/RA)"])
router.include_router(statements.router, prefix="/statements", tags=["Vendor Statements (TGQ HMPR / NDC / LCC / GDS)"])
router.include_router(lcc_detailed.router, prefix="/lcc-detailed", tags=["Vendor Statements (LCC Detailed)"])
router.include_router(ticket_details.router, prefix="/ticket-details", tags=["Ticket Details"])
router.include_router(bsp.router, prefix="/bsp", tags=["Tickets - BSP Statements"])
router.include_router(bsp_summary.router, prefix="/bsp", tags=["Tickets - BSP Summary"])
router.include_router(bsp_reconciliation.router, prefix="/bsp-reconciliation", tags=["Tickets - BSP Reconciliation"])
router.include_router(bsp_commission.router, prefix="/bsp-commission", tags=["Vendors - Commission Income"])
router.include_router(customer_statements.router, prefix="/customer-statements", tags=["Customer Statements"])
router.include_router(series_contracts.router, prefix="/series-contracts", tags=["Vendors - Series/SIT/MICE Contracts"])
