"""Report download Read Me sheet — the workbook must explain itself without the app.

No DB. Checks that Read Me always has its nine blocks in order, that the legends are rendered
from the shared vocabularies (so they cannot drift: 62 Combined columns, every flag), that the
build time is shown in UTC and IST (UTC+5:30), that excluded files carry a readable reason,
that the TGQ index line is optional, and that the blocks render through ReportWorkbook.

Run:  python -m unittest test_report_download_readme   (from backend/tests)
"""

import os
import shutil
import sys
import tempfile
import unittest
from datetime import date, datetime, timedelta, timezone

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from openpyxl import load_workbook  # noqa: E402

from app.services.report_download import columns as C  # noqa: E402
from app.services.report_download import readme as R  # noqa: E402
from app.services.report_download.readme import readme_blocks  # noqa: E402
from app.services.report_download.types import REPORT_ENGINE_VERSION, Period, ReportMeta, ReportOptions  # noqa: E402
from app.services.report_download.workbook import ReportWorkbook  # noqa: E402


def make_meta(**kw):
    base = dict(
        export_id=42, title="August close", generated_at=datetime(2026, 9, 15, 20, 0, 0),
        generated_by_name="Asha Rao", generated_by_email="asha@example.com", tenant_name="Acme Travels",
        period=Period(date(2026, 8, 1), date(2026, 8, 31)),
        options=ReportOptions(basis="transaction", bsp_scope="whole_statement", include_detail_sheets=True,
                              include_pii=False, undated_rows="include"),
        source_types=("tp-api", "bsp", "adm"),
    )
    base.update(kw)
    return ReportMeta(**base)


INCLUDED = [{
    "category": "BSP", "source_type": "bsp", "file_name": "BSP_AUG.pdf", "upload_id": "b-1",
    "uploaded_at": datetime(2026, 8, 20, 9, 30), "reference": "REF1", "rows_in_file": 120,
    "rows_included": 118, "rows_undated": 2, "rows_superseded": 0, "notes": ["changed during build"],
}, {
    "source_type": "tgq-hmpr", "file_name": "tgq.xlsx", "upload_id": "t-1", "uploaded_at": None,
    "reference": None, "rows_in_file": 10, "rows_included": 10, "rows_undated": 0, "rows_superseded": 3,
    "notes": None,
}]
EXCLUDED = [
    {"category": "BSP", "source_type": "tgq-hmpr", "file_name": "old.xlsx", "upload_id": "t-0", "reason": "unticked"},
    {"category": "LCC", "source_type": "lcc-detailed", "file_name": "lcc.csv", "upload_id": "l-1",
     "reason": "Not completed at build time"},
    {"category": "Third Party", "source_type": "tp-gds", "file_name": "gds.xlsx", "upload_id": "g-1",
     "reason": "no_rows"},
]
SHEETS = [("Read Me", 0, "This sheet"), ("Combined", 128, "One row per settlement record")]


def blocks(**kw):
    args = dict(files_included=INCLUDED, files_excluded=EXCLUDED, sheets=SHEETS,
                tgq_stats={"rows_loaded": 12345, "batches_used": 3, "truncated": False})
    args.update(kw)
    meta = args.pop("meta", None) or make_meta()
    return {b.title: b for b in readme_blocks(meta, **args)}


def kv(block):
    return {r[0]: r[1] for r in block.rows}


class ReadmeTests(unittest.TestCase):
    def test_block_titles_and_order(self):
        meta = make_meta()
        titles = [b.title for b in readme_blocks(meta, files_included=[], files_excluded=[], sheets=[], tgq_stats=None)]
        self.assertEqual(titles, [
            "Report", "Files included", "Files not included", "Sheets", "Combined column legend",
            "Transaction types", "Counts In Net", "Data flags", "Caveats",
        ])
        self.assertEqual(tuple(titles), R.BLOCK_TITLES)

    def test_report_block(self):
        rep = kv(blocks()["Report"])
        self.assertEqual(rep["Report name"], "August close")
        self.assertEqual(rep["Report ID"], "42")
        self.assertEqual(rep["Generated by"], "Asha Rao <asha@example.com>")
        self.assertEqual(rep["Workspace"], "Acme Travels")
        self.assertEqual(rep["Engine version"], REPORT_ENGINE_VERSION)
        self.assertEqual(rep["Period"], "01-Aug-2026 to 31-Aug-2026")
        self.assertEqual(rep["Date basis"], "Issue / transaction date")
        self.assertEqual(rep["BSP scope"], "Whole statements overlapping the period")
        self.assertEqual(rep["Source types"], "BSP, ADM, Third Party API")     # registry order, labels
        self.assertEqual(rep["Detail sheets"], "Yes")
        self.assertEqual(rep["Passenger contact details"], "No")
        self.assertIn("DATE_UNREADABLE", rep["Rows without a readable date"])
        self.assertEqual(rep["TGQ enrichment index"], "Rows loaded: 12,345; batches used: 3; truncated: No")
        for value in rep.values():
            self.assertTrue(value is None or isinstance(value, (str, date)))

    def test_ist_is_utc_plus_530(self):
        rep = kv(blocks()["Report"])
        self.assertEqual(rep["Generated at (UTC)"], "15-Sep-2026 20:00:00")
        self.assertEqual(rep["Generated at (IST, UTC+5:30)"], "16-Sep-2026 01:30:00")
        aware = make_meta(generated_at=datetime(2026, 9, 15, 20, 0, tzinfo=timezone(timedelta(hours=2))))
        rep = kv(blocks(meta=aware)["Report"])
        self.assertEqual(rep["Generated at (UTC)"], "15-Sep-2026 18:00:00")
        self.assertEqual(rep["Generated at (IST, UTC+5:30)"], "15-Sep-2026 23:30:00")

    def test_other_option_labels(self):
        meta = make_meta(
            title=None, export_id=None, generated_by_name=None, period=None, source_types=(),
            options=ReportOptions(basis="upload", bsp_scope="issue_date", include_detail_sheets=False,
                                  include_pii=True, undated_rows="exclude"),
        )
        rep = kv(blocks(meta=meta)["Report"])
        self.assertEqual(rep["Report name"], "Untitled report")
        self.assertIsNone(rep["Report ID"])
        self.assertEqual(rep["Generated by"], "asha@example.com")
        self.assertEqual(rep["Period"], "All dates")
        self.assertEqual(rep["Date basis"], "Upload date")
        self.assertEqual(rep["BSP scope"], "Rows issued in the period")
        self.assertEqual(rep["Detail sheets"], "No")
        self.assertEqual(rep["Passenger contact details"], "Yes")
        self.assertEqual(rep["Rows without a readable date"], "Left out of the report")

    def test_tgq_stats_optional(self):
        rep = kv(blocks(tgq_stats=None)["Report"])
        self.assertNotIn("TGQ enrichment index", rep)
        rep = kv(blocks(tgq_stats={"rows_loaded": 500000, "batches_used": 40, "truncated": True})["Report"])
        self.assertEqual(rep["TGQ enrichment index"], "Rows loaded: 500,000; batches used: 40; truncated: Yes")

    def test_files_included(self):
        b = blocks()["Files included"]
        self.assertEqual(list(b.headers), [
            "Category", "Source Type", "File", "Upload ID", "Uploaded At", "Reference", "Rows in file",
            "Rows included", "Rows w/o readable date", "Superseded rows", "Notes",
        ])
        self.assertEqual(b.rows[0], ["BSP", "BSP", "BSP_AUG.pdf", "b-1", datetime(2026, 8, 20, 9, 30), "REF1",
                                     120, 118, 2, 0, "changed during build"])
        # category filled from the registry; source key shown as its label
        self.assertEqual(b.rows[1][:3], ["BSP", "TGQ HMPR", "tgq.xlsx"])
        self.assertEqual(b.kinds[4], "datetime")

    def test_files_excluded_reasons(self):
        b = blocks()["Files not included"]
        self.assertEqual(list(b.headers), ["File", "Source Type", "Upload ID", "Reason"])
        self.assertEqual(b.rows, [
            ["old.xlsx", "TGQ HMPR", "t-0", "Unticked by you"],
            ["lcc.csv", "LCC Detailed Statement", "l-1", "Not completed at build time"],
            ["gds.xlsx", "Third Party GDS", "g-1", "No rows in period"],
        ])

    def test_empty_tables_get_a_none_row(self):
        meta = make_meta()
        bs = {b.title: b for b in readme_blocks(meta, files_included=[], files_excluded=[], sheets=[], tgq_stats=None)}
        for title in ("Files included", "Files not included", "Sheets"):
            self.assertEqual(bs[title].rows[0][0], "None", title)
            self.assertEqual(len(bs[title].rows[0]), len(bs[title].headers), title)

    def test_sheets(self):
        b = blocks()["Sheets"]
        self.assertEqual(b.rows, [["Read Me", 0, "This sheet"], ["Combined", 128, "One row per settlement record"]])

    def test_column_legend(self):
        b = blocks()["Combined column legend"]
        self.assertEqual(len(b.rows), 62)
        self.assertEqual(len(b.rows), len(C.COMBINED_COLUMNS))
        legend = {r[0]: r[1:] for r in b.rows}
        self.assertEqual(legend["Net Payable"], ["Money", "signed", "Net owed to/by the Settled With party"])
        self.assertEqual(legend["Service Fee"][:2], ["Money", "unsigned"])
        self.assertEqual(legend["Uploaded At (UTC)"][:2], ["Date & time", None])
        self.assertEqual(legend["Issue / Txn Date"][0], "Date")
        self.assertEqual(legend["Pax Count"][0], "Number")
        self.assertEqual(legend["Data Flags"][0], "Flag")
        self.assertEqual(legend["Airline PNR"], ["Text", None, None])

    def test_transaction_types_and_sign_rules(self):
        rows = blocks()["Transaction types"].rows
        self.assertEqual(len(rows), len(C.TXN_TYPES) + 1 + len(C.SIGN_RULES_TEXT))
        self.assertEqual(rows[0], ["SALE", C.TXN_TYPES["SALE"]])
        i = [r[0] for r in rows].index("Sign rules")
        self.assertEqual(i, len(C.TXN_TYPES))
        self.assertEqual([tuple(r) for r in rows[i + 1:]], list(C.SIGN_RULES_TEXT))

    def test_counts_in_net_and_flags(self):
        bs = blocks()
        self.assertEqual([tuple(r) for r in bs["Counts In Net"].rows], list(C.COUNTS_IN_NET_RULES))
        flags = bs["Data flags"].rows
        self.assertEqual(len(flags), len(C.FLAG_LEGEND))
        self.assertEqual(dict((r[0], r[1]) for r in flags), C.FLAG_LEGEND)

    def test_caveats_exact(self):
        b = blocks()["Caveats"]
        self.assertEqual([r[0] for r in b.rows], [
            "BSP values are the printed statement values (signs as printed).",
            "NDC, TGQ HMPR, ADM/ACM/RA and Third Party amounts are signed from the transaction type.",
            "BSP and Third Party API amounts carry no currency; INR is assumed.",
            "LCC Flown Report, CTA/BTA and Third Party LCC layouts were built without real samples — check the mapping.",
            "Alphanumeric BSPlink memo numbers cannot be matched to BSP rows.",
            "Third party status reflects the booking's state when the file was uploaded.",
            "TGQ enrichment uses every TGQ HMPR upload except the ones you unticked.",
            "A BSP statement completed in the last 10 minutes may not yet have its SPDR cancellation charges "
            "distributed onto CANX rows.",
        ])

    def test_every_block_is_rectangular(self):
        for b in blocks().values():
            width = len(b.headers) if b.headers is not None else len(b.rows[0])
            self.assertEqual(len(b.kinds), width, b.title)
            for r in b.rows:
                self.assertEqual(len(r), width, b.title)

    def test_renders_through_workbook(self):
        tmp = tempfile.mkdtemp(prefix="report-readme-test-")
        try:
            path = os.path.join(tmp, "r.xlsx")
            wb = ReportWorkbook(path)
            wb.write_blocks("readme", "Read Me", 1, list(blocks().values()))
            wb.save()
            ws = load_workbook(path)["Read Me"]
            col_a = [c.value for c in ws["A"]]
            for title in R.BLOCK_TITLES:
                self.assertIn(title, col_a)
            self.assertIn("SALE", col_a)
            self.assertIn("LINK_AMBIGUOUS", col_a)
        finally:
            shutil.rmtree(tmp, ignore_errors=True)


if __name__ == "__main__":
    unittest.main()
