"""The commission ledger: one row per run, one row per priced statement row.

WHY A LEDGER AND NOT MORE COLUMNS. BSP writes its answers onto `bsp_statement_rows` and
its run state onto `bsp_statements`, which works because BSP owns both. The third-party
and LCC tables hold the VENDOR's document, and a figure we derived is not part of it — and
those types have no batch header row to hang status, progress or a heartbeat on at all (a
"batch" there is a shared batch_id across the rows table, found with a GROUP BY). This
gives every source one place for both.

`commission_calculations` is keyed UNIQUE on (tenant, creator, source, source_row_id): one
CURRENT answer per statement row, upserted on re-run. The append-only alternative forces
every roll-up through a "latest run" subquery and double-counts the first time someone
forgets one. Run history lives in `commission_runs`, which is what you actually look back at.

ADDITIVE AND ZERO-BACKFILL. BSP is deliberately NOT projected into the ledger here — it
keeps its own columns and its own screen, untouched, and can be projected later as a
read-only copy. Introducing a ledger and making it BSP's source of truth in one change is
how a wrong number reaches the flagship screen.

NOTE: this was autogenerated and then hand-stripped. `--autogenerate` also emitted ~240
unrelated ALTER/DROP operations from pre-existing model-vs-database drift (NOT NULL
tightening, a users.role enum change, six dropped uploaded_tickets indexes). None of that
belongs to this change and all of it was removed. That drift is real and worth a
dedicated migration — it is just not this one.

NOTE ON REVISION IDS: this repo has reused hex-pattern ids that collide, so this uses a
descriptive one, matching the `<feature>_<NN>` convention the recent migrations use.

Revision ID: commission_ledger_01
Revises: deal_supplier_agency_01
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision = "commission_ledger_01"
down_revision = "deal_supplier_agency_01"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table('commission_runs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('batch_id', sa.String(length=100), nullable=False),
    sa.Column('direction', sa.String(length=10), server_default='inbound', nullable=False),
    sa.Column('engine_version', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=12), server_default='queued', nullable=False),
    sa.Column('mode', sa.String(length=10), server_default='queued', nullable=False),
    sa.Column('total_rows', sa.Integer(), server_default='0', nullable=False),
    sa.Column('processed_rows', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('calculated_rows', sa.Integer(), server_default='0', nullable=False),
    sa.Column('needs_data_rows', sa.Integer(), server_default='0', nullable=False),
    sa.Column('excluded_rows', sa.Integer(), server_default='0', nullable=False),
    sa.Column('reversed_rows', sa.Integer(), server_default='0', nullable=False),
    sa.Column('skipped_rows', sa.Integer(), server_default='0', nullable=False),
    sa.Column('unmatched_rows', sa.Integer(), server_default='0', nullable=False),
    sa.Column('pending_rows', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error_rows', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_incentive', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_iata', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('declared_commission_total', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('declared_incentive_total', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('variance_total', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('variance_unverified_rows', sa.Integer(), server_default='0', nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commission_runs_batch_id'), 'commission_runs', ['batch_id'], unique=False)
    op.create_index(op.f('ix_commission_runs_created_by_id'), 'commission_runs', ['created_by_id'], unique=False)
    op.create_index('ix_commission_runs_lookup', 'commission_runs', ['tenant_id', 'created_by_id', 'source', 'batch_id'], unique=False)
    op.create_index(op.f('ix_commission_runs_started_at'), 'commission_runs', ['started_at'], unique=False)
    op.create_index(op.f('ix_commission_runs_tenant_id'), 'commission_runs', ['tenant_id'], unique=False)
    op.create_table('commission_calculations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('run_id', sa.BigInteger(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('batch_id', sa.String(length=100), nullable=False),
    sa.Column('source_row_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('matched_deal_id', sa.BigInteger(), nullable=True),
    sa.Column('matched_deal_type', sa.String(length=10), nullable=True),
    sa.Column('matched_deal_name', sa.String(length=255), nullable=True),
    sa.Column('matched_deal_no', sa.String(length=20), nullable=True),
    sa.Column('supplier_match_by', sa.String(length=12), nullable=True),
    sa.Column('incentive', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('iata_commission', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('incentive_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('skipped_criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('unconfirmed_criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('airline_name', sa.String(length=255), nullable=True),
    sa.Column('airline_id', sa.Integer(), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('travel_date', sa.Date(), nullable=True),
    sa.Column('segment_type', sa.String(length=20), nullable=True),
    sa.Column('booking_class', sa.String(length=30), nullable=True),
    sa.Column('sector', sa.String(length=255), nullable=True),
    sa.Column('fare_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('yq', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('yr', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('ancillary_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('declared_commission', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('declared_incentive', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('declared_tds', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('declared_net', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('declared_net_ok', sa.Boolean(), nullable=True),
    sa.Column('variance_commission', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('variance_incentive', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('variance_total', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('document_number', sa.String(length=40), nullable=True),
    sa.Column('ticket_number', sa.String(length=40), nullable=True),
    sa.Column('pnr', sa.String(length=40), nullable=True),
    sa.Column('passenger_name', sa.String(length=255), nullable=True),
    sa.Column('transaction_type', sa.String(length=24), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['matched_deal_id'], ['deals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['commission_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'created_by_id', 'source', 'source_row_id', name='uq_commission_calc_source_row')
    )
    op.create_index('ix_commission_calc_batch', 'commission_calculations', ['source', 'batch_id', 'status'], unique=False)
    op.create_index(op.f('ix_commission_calculations_batch_id'), 'commission_calculations', ['batch_id'], unique=False)
    op.create_index(op.f('ix_commission_calculations_created_by_id'), 'commission_calculations', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_commission_calculations_run_id'), 'commission_calculations', ['run_id'], unique=False)
    op.create_index(op.f('ix_commission_calculations_tenant_id'), 'commission_calculations', ['tenant_id'], unique=False)


def downgrade() -> None:
    op.drop_index("ix_commission_calculations_tenant_id", table_name="commission_calculations")
    op.drop_index("ix_commission_calculations_run_id", table_name="commission_calculations")
    op.drop_index("ix_commission_calculations_created_by_id", table_name="commission_calculations")
    op.drop_index("ix_commission_calculations_batch_id", table_name="commission_calculations")
    op.drop_index("ix_commission_calc_batch", table_name="commission_calculations")
    op.drop_table("commission_calculations")
    op.drop_index("ix_commission_runs_tenant_id", table_name="commission_runs")
    op.drop_index("ix_commission_runs_started_at", table_name="commission_runs")
    op.drop_index("ix_commission_runs_lookup", table_name="commission_runs")
    op.drop_index("ix_commission_runs_created_by_id", table_name="commission_runs")
    op.drop_index("ix_commission_runs_batch_id", table_name="commission_runs")
    op.drop_table("commission_runs")
